<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $assessmentInfo['title'] }} Results</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 3px solid #3b82f6;
        }
        .header h1 {
            color: #1e40af;
            margin-bottom: 10px;
        }
        .score-box {
            background: #eff6ff;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            margin: 20px 0;
        }
        .score-box .score {
            font-size: 48px;
            font-weight: bold;
            color: #1e40af;
        }
        .section {
            margin: 30px 0;
        }
        .section h2 {
            color: #1e40af;
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 10px;
            margin-bottom: 15px;
        }
        .score-item {
            display: flex;
            justify-content: space-between;
            margin: 10px 0;
            padding: 10px;
            background: #f9fafb;
            border-radius: 4px;
        }
        .score-item .label {
            font-weight: bold;
            text-transform: capitalize;
        }
        .score-item .value {
            color: #1e40af;
            font-weight: bold;
        }
        .recommendation {
            margin: 10px 0;
            padding: 15px;
            background: #f0f9ff;
            border-left: 4px solid #3b82f6;
            border-radius: 4px;
        }
        .analysis {
            white-space: pre-line;
            background: #f9fafb;
            padding: 20px;
            border-radius: 8px;
            margin: 15px 0;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #e5e7eb;
            text-align: center;
            color: #6b7280;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $assessmentInfo['title'] }}</h1>
        <p>Assessment Results Report</p>
        <p><strong>Completed:</strong> {{ $result->completed_at->format('F j, Y') }}</p>
        <p><strong>Candidate:</strong> {{ $result->user->name }}</p>
    </div>

    <div class="score-box">
        <div class="score">{{ $result->overall_score }}%</div>
        <p>Overall Score</p>
    </div>

    <div class="section">
        <h2>Score Breakdown</h2>
        @foreach($result->scores as $category => $score)
            <div class="score-item">
                <span class="label">{{ str_replace('_', ' ', $category) }}</span>
                <span class="value">{{ $score }}%</span>
            </div>
        @endforeach
    </div>

    <div class="section">
        <h2>AI Analysis</h2>
        <div class="analysis">{{ $result->ai_analysis }}</div>
    </div>

    @if(!empty($result->recommendations))
        <div class="section">
            <h2>Recommendations</h2>
            @foreach($result->recommendations as $index => $recommendation)
                <div class="recommendation">
                    <strong>{{ $index + 1 }}.</strong> {{ $recommendation }}
                </div>
            @endforeach
        </div>
    @endif

    <div class="footer">
        <p>Generated by SpeedJobs Africa Career Assessment System</p>
        <p>This report is confidential and intended for the candidate's personal use only.</p>
    </div>
</body>
</html>
